"""add first_name and last_name to admins

Revision ID: 6a1f068be7c5
Revises: a2330b9bedb1
Create Date: 2026-02-20 18:23:22.411872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1f068be7c5'
down_revision = 'a2330b9bedb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add as nullable first so existing rows don't violate the constraint
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=True))

    # Back-fill existing admin rows with a placeholder
    op.execute("UPDATE admins SET first_name = '', last_name = '' WHERE first_name IS NULL")

    # Now tighten to non-nullable
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('first_name', existing_type=sa.String(length=80), nullable=False)
        batch_op.alter_column('last_name', existing_type=sa.String(length=80), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
    # ### end Alembic commands ###
